#!/usr/bin/env bash
#This script show "Best school" 9 times and "Hi" one time when the iterator is equal to 9

i=0
while [ $i -lt 10 ];
do
    if [ $i -eq 9 ]
    then
    echo "Hi"
    fi
    echo "Best School"
    i=$(( i+1 ))
done
