#!/usr/bin/env bash
#configuring firewalls ufw
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y ufw
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
